---

- name: Install nginx
  apt: name=nginx state=latest

- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/sites-enabled/{{ item.from }}-acme
  vars:
    domain_name: "{{ item.from }}"
  with_items: "{{ proxies }}"

- name: Reload nginx to activate letsencrypt site
  service: name=nginx state=restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ item.email }} --agree-tos -d {{ item.from }}
  args:
    creates: /etc/letsencrypt/live/{{ item.from }}
  with_items: "{{ proxies }}"

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-le.j2
    dest: /etc/nginx/sites-enabled/{{ item.from }}-le
  vars:
    from_addr: "{{ item.from }}"
    to_addr: "{{ item.to }}"
  with_items: "{{ proxies }}"

- name: Install simple proxies
  template:
    src: templates/nginx-simple-proxy.j2
    dest: /etc/nginx/sites-enabled/{{ item.from }}-{{ item.from_port }}-simple-proxy
  vars:
    from_addr: "{{ item.from }}"
    from_port: "{{ item.from_port }}"
    to_addr: "{{ item.to }}"
  with_items: "{{ simple_proxies }}"

- name: Reload nginx to activate specified site
  service: name=nginx state=restarted

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ item.email }} --agree-tos -d {{ item.from }} && service nginx reload
  with_items: "{{ proxies }}"
